version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres-data:
  cache:
    driver: local
