// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shammianand/go-auth/ent/auditlogs"
	"github.com/shammianand/go-auth/ent/predicate"
)

// AuditLogsDelete is the builder for deleting a AuditLogs entity.
type AuditLogsDelete struct {
	config
	hooks    []Hook
	mutation *AuditLogsMutation
}

// Where appends a list predicates to the AuditLogsDelete builder.
func (ald *AuditLogsDelete) Where(ps ...predicate.AuditLogs) *AuditLogsDelete {
	ald.mutation.Where(ps...)
	return ald
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ald *AuditLogsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ald.sqlExec, ald.mutation, ald.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ald *AuditLogsDelete) ExecX(ctx context.Context) int {
	n, err := ald.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ald *AuditLogsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(auditlogs.Table, sqlgraph.NewFieldSpec(auditlogs.FieldID, field.TypeUUID))
	if ps := ald.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ald.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ald.mutation.done = true
	return affected, err
}

// AuditLogsDeleteOne is the builder for deleting a single AuditLogs entity.
type AuditLogsDeleteOne struct {
	ald *AuditLogsDelete
}

// Where appends a list predicates to the AuditLogsDelete builder.
func (aldo *AuditLogsDeleteOne) Where(ps ...predicate.AuditLogs) *AuditLogsDeleteOne {
	aldo.ald.mutation.Where(ps...)
	return aldo
}

// Exec executes the deletion query.
func (aldo *AuditLogsDeleteOne) Exec(ctx context.Context) error {
	n, err := aldo.ald.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{auditlogs.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aldo *AuditLogsDeleteOne) ExecX(ctx context.Context) {
	if err := aldo.Exec(ctx); err != nil {
		panic(err)
	}
}
