// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/shammianand/go-auth/ent/emailverifications"
)

// EmailVerifications is the model entity for the EmailVerifications schema.
type EmailVerifications struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// User requesting verification
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// When this token expires
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// IsUsed holds the value of the "is_used" field.
	IsUsed bool `json:"is_used,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress string `json:"ip_address,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailVerifications) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailverifications.FieldIsUsed:
			values[i] = new(sql.NullBool)
		case emailverifications.FieldEmail, emailverifications.FieldToken, emailverifications.FieldIPAddress:
			values[i] = new(sql.NullString)
		case emailverifications.FieldExpiresAt, emailverifications.FieldUsedAt, emailverifications.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case emailverifications.FieldID, emailverifications.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailVerifications fields.
func (ev *EmailVerifications) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailverifications.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ev.ID = *value
			}
		case emailverifications.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				ev.UserID = *value
			}
		case emailverifications.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				ev.Email = value.String
			}
		case emailverifications.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				ev.Token = value.String
			}
		case emailverifications.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				ev.ExpiresAt = value.Time
			}
		case emailverifications.FieldIsUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_used", values[i])
			} else if value.Valid {
				ev.IsUsed = value.Bool
			}
		case emailverifications.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				ev.UsedAt = new(time.Time)
				*ev.UsedAt = value.Time
			}
		case emailverifications.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				ev.IPAddress = value.String
			}
		case emailverifications.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ev.CreatedAt = value.Time
			}
		default:
			ev.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailVerifications.
// This includes values selected through modifiers, order, etc.
func (ev *EmailVerifications) Value(name string) (ent.Value, error) {
	return ev.selectValues.Get(name)
}

// Update returns a builder for updating this EmailVerifications.
// Note that you need to call EmailVerifications.Unwrap() before calling this method if this EmailVerifications
// was returned from a transaction, and the transaction was committed or rolled back.
func (ev *EmailVerifications) Update() *EmailVerificationsUpdateOne {
	return NewEmailVerificationsClient(ev.config).UpdateOne(ev)
}

// Unwrap unwraps the EmailVerifications entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ev *EmailVerifications) Unwrap() *EmailVerifications {
	_tx, ok := ev.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmailVerifications is not a transactional entity")
	}
	ev.config.driver = _tx.drv
	return ev
}

// String implements the fmt.Stringer.
func (ev *EmailVerifications) String() string {
	var builder strings.Builder
	builder.WriteString("EmailVerifications(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ev.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ev.UserID))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(ev.Email)
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(ev.Token)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(ev.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_used=")
	builder.WriteString(fmt.Sprintf("%v", ev.IsUsed))
	builder.WriteString(", ")
	if v := ev.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(ev.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ev.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EmailVerificationsSlice is a parsable slice of EmailVerifications.
type EmailVerificationsSlice []*EmailVerifications
