// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shammianand/go-auth/ent/emailverifications"
	"github.com/shammianand/go-auth/ent/predicate"
)

// EmailVerificationsQuery is the builder for querying EmailVerifications entities.
type EmailVerificationsQuery struct {
	config
	ctx        *QueryContext
	order      []emailverifications.OrderOption
	inters     []Interceptor
	predicates []predicate.EmailVerifications
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EmailVerificationsQuery builder.
func (evq *EmailVerificationsQuery) Where(ps ...predicate.EmailVerifications) *EmailVerificationsQuery {
	evq.predicates = append(evq.predicates, ps...)
	return evq
}

// Limit the number of records to be returned by this query.
func (evq *EmailVerificationsQuery) Limit(limit int) *EmailVerificationsQuery {
	evq.ctx.Limit = &limit
	return evq
}

// Offset to start from.
func (evq *EmailVerificationsQuery) Offset(offset int) *EmailVerificationsQuery {
	evq.ctx.Offset = &offset
	return evq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (evq *EmailVerificationsQuery) Unique(unique bool) *EmailVerificationsQuery {
	evq.ctx.Unique = &unique
	return evq
}

// Order specifies how the records should be ordered.
func (evq *EmailVerificationsQuery) Order(o ...emailverifications.OrderOption) *EmailVerificationsQuery {
	evq.order = append(evq.order, o...)
	return evq
}

// First returns the first EmailVerifications entity from the query.
// Returns a *NotFoundError when no EmailVerifications was found.
func (evq *EmailVerificationsQuery) First(ctx context.Context) (*EmailVerifications, error) {
	nodes, err := evq.Limit(1).All(setContextOp(ctx, evq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{emailverifications.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (evq *EmailVerificationsQuery) FirstX(ctx context.Context) *EmailVerifications {
	node, err := evq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EmailVerifications ID from the query.
// Returns a *NotFoundError when no EmailVerifications ID was found.
func (evq *EmailVerificationsQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = evq.Limit(1).IDs(setContextOp(ctx, evq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{emailverifications.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (evq *EmailVerificationsQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := evq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EmailVerifications entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EmailVerifications entity is found.
// Returns a *NotFoundError when no EmailVerifications entities are found.
func (evq *EmailVerificationsQuery) Only(ctx context.Context) (*EmailVerifications, error) {
	nodes, err := evq.Limit(2).All(setContextOp(ctx, evq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{emailverifications.Label}
	default:
		return nil, &NotSingularError{emailverifications.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (evq *EmailVerificationsQuery) OnlyX(ctx context.Context) *EmailVerifications {
	node, err := evq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EmailVerifications ID in the query.
// Returns a *NotSingularError when more than one EmailVerifications ID is found.
// Returns a *NotFoundError when no entities are found.
func (evq *EmailVerificationsQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = evq.Limit(2).IDs(setContextOp(ctx, evq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{emailverifications.Label}
	default:
		err = &NotSingularError{emailverifications.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (evq *EmailVerificationsQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := evq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EmailVerificationsSlice.
func (evq *EmailVerificationsQuery) All(ctx context.Context) ([]*EmailVerifications, error) {
	ctx = setContextOp(ctx, evq.ctx, "All")
	if err := evq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EmailVerifications, *EmailVerificationsQuery]()
	return withInterceptors[[]*EmailVerifications](ctx, evq, qr, evq.inters)
}

// AllX is like All, but panics if an error occurs.
func (evq *EmailVerificationsQuery) AllX(ctx context.Context) []*EmailVerifications {
	nodes, err := evq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EmailVerifications IDs.
func (evq *EmailVerificationsQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if evq.ctx.Unique == nil && evq.path != nil {
		evq.Unique(true)
	}
	ctx = setContextOp(ctx, evq.ctx, "IDs")
	if err = evq.Select(emailverifications.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (evq *EmailVerificationsQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := evq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (evq *EmailVerificationsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, evq.ctx, "Count")
	if err := evq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, evq, querierCount[*EmailVerificationsQuery](), evq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (evq *EmailVerificationsQuery) CountX(ctx context.Context) int {
	count, err := evq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (evq *EmailVerificationsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, evq.ctx, "Exist")
	switch _, err := evq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (evq *EmailVerificationsQuery) ExistX(ctx context.Context) bool {
	exist, err := evq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EmailVerificationsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (evq *EmailVerificationsQuery) Clone() *EmailVerificationsQuery {
	if evq == nil {
		return nil
	}
	return &EmailVerificationsQuery{
		config:     evq.config,
		ctx:        evq.ctx.Clone(),
		order:      append([]emailverifications.OrderOption{}, evq.order...),
		inters:     append([]Interceptor{}, evq.inters...),
		predicates: append([]predicate.EmailVerifications{}, evq.predicates...),
		// clone intermediate query.
		sql:  evq.sql.Clone(),
		path: evq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EmailVerifications.Query().
//		GroupBy(emailverifications.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (evq *EmailVerificationsQuery) GroupBy(field string, fields ...string) *EmailVerificationsGroupBy {
	evq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EmailVerificationsGroupBy{build: evq}
	grbuild.flds = &evq.ctx.Fields
	grbuild.label = emailverifications.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.EmailVerifications.Query().
//		Select(emailverifications.FieldUserID).
//		Scan(ctx, &v)
func (evq *EmailVerificationsQuery) Select(fields ...string) *EmailVerificationsSelect {
	evq.ctx.Fields = append(evq.ctx.Fields, fields...)
	sbuild := &EmailVerificationsSelect{EmailVerificationsQuery: evq}
	sbuild.label = emailverifications.Label
	sbuild.flds, sbuild.scan = &evq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EmailVerificationsSelect configured with the given aggregations.
func (evq *EmailVerificationsQuery) Aggregate(fns ...AggregateFunc) *EmailVerificationsSelect {
	return evq.Select().Aggregate(fns...)
}

func (evq *EmailVerificationsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range evq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, evq); err != nil {
				return err
			}
		}
	}
	for _, f := range evq.ctx.Fields {
		if !emailverifications.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if evq.path != nil {
		prev, err := evq.path(ctx)
		if err != nil {
			return err
		}
		evq.sql = prev
	}
	return nil
}

func (evq *EmailVerificationsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EmailVerifications, error) {
	var (
		nodes = []*EmailVerifications{}
		_spec = evq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EmailVerifications).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EmailVerifications{config: evq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, evq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (evq *EmailVerificationsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := evq.querySpec()
	_spec.Node.Columns = evq.ctx.Fields
	if len(evq.ctx.Fields) > 0 {
		_spec.Unique = evq.ctx.Unique != nil && *evq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, evq.driver, _spec)
}

func (evq *EmailVerificationsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(emailverifications.Table, emailverifications.Columns, sqlgraph.NewFieldSpec(emailverifications.FieldID, field.TypeUUID))
	_spec.From = evq.sql
	if unique := evq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if evq.path != nil {
		_spec.Unique = true
	}
	if fields := evq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailverifications.FieldID)
		for i := range fields {
			if fields[i] != emailverifications.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := evq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := evq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := evq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := evq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (evq *EmailVerificationsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(evq.driver.Dialect())
	t1 := builder.Table(emailverifications.Table)
	columns := evq.ctx.Fields
	if len(columns) == 0 {
		columns = emailverifications.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if evq.sql != nil {
		selector = evq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if evq.ctx.Unique != nil && *evq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range evq.predicates {
		p(selector)
	}
	for _, p := range evq.order {
		p(selector)
	}
	if offset := evq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := evq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EmailVerificationsGroupBy is the group-by builder for EmailVerifications entities.
type EmailVerificationsGroupBy struct {
	selector
	build *EmailVerificationsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (evgb *EmailVerificationsGroupBy) Aggregate(fns ...AggregateFunc) *EmailVerificationsGroupBy {
	evgb.fns = append(evgb.fns, fns...)
	return evgb
}

// Scan applies the selector query and scans the result into the given value.
func (evgb *EmailVerificationsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, evgb.build.ctx, "GroupBy")
	if err := evgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmailVerificationsQuery, *EmailVerificationsGroupBy](ctx, evgb.build, evgb, evgb.build.inters, v)
}

func (evgb *EmailVerificationsGroupBy) sqlScan(ctx context.Context, root *EmailVerificationsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(evgb.fns))
	for _, fn := range evgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*evgb.flds)+len(evgb.fns))
		for _, f := range *evgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*evgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := evgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EmailVerificationsSelect is the builder for selecting fields of EmailVerifications entities.
type EmailVerificationsSelect struct {
	*EmailVerificationsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (evs *EmailVerificationsSelect) Aggregate(fns ...AggregateFunc) *EmailVerificationsSelect {
	evs.fns = append(evs.fns, fns...)
	return evs
}

// Scan applies the selector query and scans the result into the given value.
func (evs *EmailVerificationsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, evs.ctx, "Select")
	if err := evs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmailVerificationsQuery, *EmailVerificationsSelect](ctx, evs.EmailVerificationsQuery, evs, evs.inters, v)
}

func (evs *EmailVerificationsSelect) sqlScan(ctx context.Context, root *EmailVerificationsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(evs.fns))
	for _, fn := range evs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*evs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := evs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
