// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shammianand/go-auth/ent/passwordresets"
	"github.com/shammianand/go-auth/ent/predicate"
)

// PasswordResetsDelete is the builder for deleting a PasswordResets entity.
type PasswordResetsDelete struct {
	config
	hooks    []Hook
	mutation *PasswordResetsMutation
}

// Where appends a list predicates to the PasswordResetsDelete builder.
func (prd *PasswordResetsDelete) Where(ps ...predicate.PasswordResets) *PasswordResetsDelete {
	prd.mutation.Where(ps...)
	return prd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (prd *PasswordResetsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, prd.sqlExec, prd.mutation, prd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (prd *PasswordResetsDelete) ExecX(ctx context.Context) int {
	n, err := prd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (prd *PasswordResetsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(passwordresets.Table, sqlgraph.NewFieldSpec(passwordresets.FieldID, field.TypeUUID))
	if ps := prd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, prd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	prd.mutation.done = true
	return affected, err
}

// PasswordResetsDeleteOne is the builder for deleting a single PasswordResets entity.
type PasswordResetsDeleteOne struct {
	prd *PasswordResetsDelete
}

// Where appends a list predicates to the PasswordResetsDelete builder.
func (prdo *PasswordResetsDeleteOne) Where(ps ...predicate.PasswordResets) *PasswordResetsDeleteOne {
	prdo.prd.mutation.Where(ps...)
	return prdo
}

// Exec executes the deletion query.
func (prdo *PasswordResetsDeleteOne) Exec(ctx context.Context) error {
	n, err := prdo.prd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{passwordresets.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (prdo *PasswordResetsDeleteOne) ExecX(ctx context.Context) {
	if err := prdo.Exec(ctx); err != nil {
		panic(err)
	}
}
