// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shammianand/go-auth/ent/passwordresets"
)

// PasswordResetsCreate is the builder for creating a PasswordResets entity.
type PasswordResetsCreate struct {
	config
	mutation *PasswordResetsMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (prc *PasswordResetsCreate) SetUserID(u uuid.UUID) *PasswordResetsCreate {
	prc.mutation.SetUserID(u)
	return prc
}

// SetEmail sets the "email" field.
func (prc *PasswordResetsCreate) SetEmail(s string) *PasswordResetsCreate {
	prc.mutation.SetEmail(s)
	return prc
}

// SetToken sets the "token" field.
func (prc *PasswordResetsCreate) SetToken(s string) *PasswordResetsCreate {
	prc.mutation.SetToken(s)
	return prc
}

// SetExpiresAt sets the "expires_at" field.
func (prc *PasswordResetsCreate) SetExpiresAt(t time.Time) *PasswordResetsCreate {
	prc.mutation.SetExpiresAt(t)
	return prc
}

// SetIsUsed sets the "is_used" field.
func (prc *PasswordResetsCreate) SetIsUsed(b bool) *PasswordResetsCreate {
	prc.mutation.SetIsUsed(b)
	return prc
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (prc *PasswordResetsCreate) SetNillableIsUsed(b *bool) *PasswordResetsCreate {
	if b != nil {
		prc.SetIsUsed(*b)
	}
	return prc
}

// SetUsedAt sets the "used_at" field.
func (prc *PasswordResetsCreate) SetUsedAt(t time.Time) *PasswordResetsCreate {
	prc.mutation.SetUsedAt(t)
	return prc
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (prc *PasswordResetsCreate) SetNillableUsedAt(t *time.Time) *PasswordResetsCreate {
	if t != nil {
		prc.SetUsedAt(*t)
	}
	return prc
}

// SetIPAddress sets the "ip_address" field.
func (prc *PasswordResetsCreate) SetIPAddress(s string) *PasswordResetsCreate {
	prc.mutation.SetIPAddress(s)
	return prc
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (prc *PasswordResetsCreate) SetNillableIPAddress(s *string) *PasswordResetsCreate {
	if s != nil {
		prc.SetIPAddress(*s)
	}
	return prc
}

// SetCreatedAt sets the "created_at" field.
func (prc *PasswordResetsCreate) SetCreatedAt(t time.Time) *PasswordResetsCreate {
	prc.mutation.SetCreatedAt(t)
	return prc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (prc *PasswordResetsCreate) SetNillableCreatedAt(t *time.Time) *PasswordResetsCreate {
	if t != nil {
		prc.SetCreatedAt(*t)
	}
	return prc
}

// SetID sets the "id" field.
func (prc *PasswordResetsCreate) SetID(u uuid.UUID) *PasswordResetsCreate {
	prc.mutation.SetID(u)
	return prc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (prc *PasswordResetsCreate) SetNillableID(u *uuid.UUID) *PasswordResetsCreate {
	if u != nil {
		prc.SetID(*u)
	}
	return prc
}

// Mutation returns the PasswordResetsMutation object of the builder.
func (prc *PasswordResetsCreate) Mutation() *PasswordResetsMutation {
	return prc.mutation
}

// Save creates the PasswordResets in the database.
func (prc *PasswordResetsCreate) Save(ctx context.Context) (*PasswordResets, error) {
	prc.defaults()
	return withHooks(ctx, prc.sqlSave, prc.mutation, prc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (prc *PasswordResetsCreate) SaveX(ctx context.Context) *PasswordResets {
	v, err := prc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (prc *PasswordResetsCreate) Exec(ctx context.Context) error {
	_, err := prc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (prc *PasswordResetsCreate) ExecX(ctx context.Context) {
	if err := prc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (prc *PasswordResetsCreate) defaults() {
	if _, ok := prc.mutation.IsUsed(); !ok {
		v := passwordresets.DefaultIsUsed
		prc.mutation.SetIsUsed(v)
	}
	if _, ok := prc.mutation.CreatedAt(); !ok {
		v := passwordresets.DefaultCreatedAt()
		prc.mutation.SetCreatedAt(v)
	}
	if _, ok := prc.mutation.ID(); !ok {
		v := passwordresets.DefaultID()
		prc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (prc *PasswordResetsCreate) check() error {
	if _, ok := prc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PasswordResets.user_id"`)}
	}
	if _, ok := prc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "PasswordResets.email"`)}
	}
	if v, ok := prc.mutation.Email(); ok {
		if err := passwordresets.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "PasswordResets.email": %w`, err)}
		}
	}
	if _, ok := prc.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "PasswordResets.token"`)}
	}
	if v, ok := prc.mutation.Token(); ok {
		if err := passwordresets.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "PasswordResets.token": %w`, err)}
		}
	}
	if _, ok := prc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "PasswordResets.expires_at"`)}
	}
	if _, ok := prc.mutation.IsUsed(); !ok {
		return &ValidationError{Name: "is_used", err: errors.New(`ent: missing required field "PasswordResets.is_used"`)}
	}
	if _, ok := prc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PasswordResets.created_at"`)}
	}
	return nil
}

func (prc *PasswordResetsCreate) sqlSave(ctx context.Context) (*PasswordResets, error) {
	if err := prc.check(); err != nil {
		return nil, err
	}
	_node, _spec := prc.createSpec()
	if err := sqlgraph.CreateNode(ctx, prc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	prc.mutation.id = &_node.ID
	prc.mutation.done = true
	return _node, nil
}

func (prc *PasswordResetsCreate) createSpec() (*PasswordResets, *sqlgraph.CreateSpec) {
	var (
		_node = &PasswordResets{config: prc.config}
		_spec = sqlgraph.NewCreateSpec(passwordresets.Table, sqlgraph.NewFieldSpec(passwordresets.FieldID, field.TypeUUID))
	)
	if id, ok := prc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := prc.mutation.UserID(); ok {
		_spec.SetField(passwordresets.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := prc.mutation.Email(); ok {
		_spec.SetField(passwordresets.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := prc.mutation.Token(); ok {
		_spec.SetField(passwordresets.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := prc.mutation.ExpiresAt(); ok {
		_spec.SetField(passwordresets.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := prc.mutation.IsUsed(); ok {
		_spec.SetField(passwordresets.FieldIsUsed, field.TypeBool, value)
		_node.IsUsed = value
	}
	if value, ok := prc.mutation.UsedAt(); ok {
		_spec.SetField(passwordresets.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := prc.mutation.IPAddress(); ok {
		_spec.SetField(passwordresets.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := prc.mutation.CreatedAt(); ok {
		_spec.SetField(passwordresets.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// PasswordResetsCreateBulk is the builder for creating many PasswordResets entities in bulk.
type PasswordResetsCreateBulk struct {
	config
	err      error
	builders []*PasswordResetsCreate
}

// Save creates the PasswordResets entities in the database.
func (prcb *PasswordResetsCreateBulk) Save(ctx context.Context) ([]*PasswordResets, error) {
	if prcb.err != nil {
		return nil, prcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(prcb.builders))
	nodes := make([]*PasswordResets, len(prcb.builders))
	mutators := make([]Mutator, len(prcb.builders))
	for i := range prcb.builders {
		func(i int, root context.Context) {
			builder := prcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasswordResetsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, prcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, prcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, prcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (prcb *PasswordResetsCreateBulk) SaveX(ctx context.Context) []*PasswordResets {
	v, err := prcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (prcb *PasswordResetsCreateBulk) Exec(ctx context.Context) error {
	_, err := prcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (prcb *PasswordResetsCreateBulk) ExecX(ctx context.Context) {
	if err := prcb.Exec(ctx); err != nil {
		panic(err)
	}
}
