// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shammianand/go-auth/ent/permissions"
	"github.com/shammianand/go-auth/ent/rolepermissions"
)

// PermissionsCreate is the builder for creating a Permissions entity.
type PermissionsCreate struct {
	config
	mutation *PermissionsMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (pc *PermissionsCreate) SetCode(s string) *PermissionsCreate {
	pc.mutation.SetCode(s)
	return pc
}

// SetName sets the "name" field.
func (pc *PermissionsCreate) SetName(s string) *PermissionsCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetDescription sets the "description" field.
func (pc *PermissionsCreate) SetDescription(s string) *PermissionsCreate {
	pc.mutation.SetDescription(s)
	return pc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableDescription(s *string) *PermissionsCreate {
	if s != nil {
		pc.SetDescription(*s)
	}
	return pc
}

// SetResource sets the "resource" field.
func (pc *PermissionsCreate) SetResource(s string) *PermissionsCreate {
	pc.mutation.SetResource(s)
	return pc
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableResource(s *string) *PermissionsCreate {
	if s != nil {
		pc.SetResource(*s)
	}
	return pc
}

// SetAction sets the "action" field.
func (pc *PermissionsCreate) SetAction(s string) *PermissionsCreate {
	pc.mutation.SetAction(s)
	return pc
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableAction(s *string) *PermissionsCreate {
	if s != nil {
		pc.SetAction(*s)
	}
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PermissionsCreate) SetCreatedAt(t time.Time) *PermissionsCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableCreatedAt(t *time.Time) *PermissionsCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PermissionsCreate) SetUpdatedAt(t time.Time) *PermissionsCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableUpdatedAt(t *time.Time) *PermissionsCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PermissionsCreate) SetID(i int) *PermissionsCreate {
	pc.mutation.SetID(i)
	return pc
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermissions entity by IDs.
func (pc *PermissionsCreate) AddRolePermissionIDs(ids ...int) *PermissionsCreate {
	pc.mutation.AddRolePermissionIDs(ids...)
	return pc
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermissions entity.
func (pc *PermissionsCreate) AddRolePermissions(r ...*RolePermissions) *PermissionsCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pc.AddRolePermissionIDs(ids...)
}

// Mutation returns the PermissionsMutation object of the builder.
func (pc *PermissionsCreate) Mutation() *PermissionsMutation {
	return pc.mutation
}

// Save creates the Permissions in the database.
func (pc *PermissionsCreate) Save(ctx context.Context) (*Permissions, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PermissionsCreate) SaveX(ctx context.Context) *Permissions {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PermissionsCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PermissionsCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PermissionsCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := permissions.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := permissions.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PermissionsCreate) check() error {
	if _, ok := pc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Permissions.code"`)}
	}
	if v, ok := pc.mutation.Code(); ok {
		if err := permissions.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Permissions.code": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Permissions.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := permissions.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Permissions.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Permissions.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Permissions.updated_at"`)}
	}
	return nil
}

func (pc *PermissionsCreate) sqlSave(ctx context.Context) (*Permissions, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PermissionsCreate) createSpec() (*Permissions, *sqlgraph.CreateSpec) {
	var (
		_node = &Permissions{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(permissions.Table, sqlgraph.NewFieldSpec(permissions.FieldID, field.TypeInt))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.Code(); ok {
		_spec.SetField(permissions.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(permissions.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Description(); ok {
		_spec.SetField(permissions.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := pc.mutation.Resource(); ok {
		_spec.SetField(permissions.FieldResource, field.TypeString, value)
		_node.Resource = value
	}
	if value, ok := pc.mutation.Action(); ok {
		_spec.SetField(permissions.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(permissions.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(permissions.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := pc.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permissions.RolePermissionsTable,
			Columns: []string{permissions.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PermissionsCreateBulk is the builder for creating many Permissions entities in bulk.
type PermissionsCreateBulk struct {
	config
	err      error
	builders []*PermissionsCreate
}

// Save creates the Permissions entities in the database.
func (pcb *PermissionsCreateBulk) Save(ctx context.Context) ([]*Permissions, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Permissions, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PermissionsCreateBulk) SaveX(ctx context.Context) []*Permissions {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PermissionsCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PermissionsCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
