// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shammianand/go-auth/ent/predicate"
	"github.com/shammianand/go-auth/ent/rolepermissions"
	"github.com/shammianand/go-auth/ent/roles"
	"github.com/shammianand/go-auth/ent/userroles"
)

// RolesQuery is the builder for querying Roles entities.
type RolesQuery struct {
	config
	ctx                 *QueryContext
	order               []roles.OrderOption
	inters              []Interceptor
	predicates          []predicate.Roles
	withUserRoles       *UserRolesQuery
	withRolePermissions *RolePermissionsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RolesQuery builder.
func (rq *RolesQuery) Where(ps ...predicate.Roles) *RolesQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *RolesQuery) Limit(limit int) *RolesQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *RolesQuery) Offset(offset int) *RolesQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *RolesQuery) Unique(unique bool) *RolesQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *RolesQuery) Order(o ...roles.OrderOption) *RolesQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryUserRoles chains the current query on the "user_roles" edge.
func (rq *RolesQuery) QueryUserRoles() *UserRolesQuery {
	query := (&UserRolesClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roles.Table, roles.FieldID, selector),
			sqlgraph.To(userroles.Table, userroles.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, roles.UserRolesTable, roles.UserRolesColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRolePermissions chains the current query on the "role_permissions" edge.
func (rq *RolesQuery) QueryRolePermissions() *RolePermissionsQuery {
	query := (&RolePermissionsClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roles.Table, roles.FieldID, selector),
			sqlgraph.To(rolepermissions.Table, rolepermissions.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, roles.RolePermissionsTable, roles.RolePermissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Roles entity from the query.
// Returns a *NotFoundError when no Roles was found.
func (rq *RolesQuery) First(ctx context.Context) (*Roles, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roles.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *RolesQuery) FirstX(ctx context.Context) *Roles {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Roles ID from the query.
// Returns a *NotFoundError when no Roles ID was found.
func (rq *RolesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roles.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *RolesQuery) FirstIDX(ctx context.Context) int {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Roles entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Roles entity is found.
// Returns a *NotFoundError when no Roles entities are found.
func (rq *RolesQuery) Only(ctx context.Context) (*Roles, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roles.Label}
	default:
		return nil, &NotSingularError{roles.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *RolesQuery) OnlyX(ctx context.Context) *Roles {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Roles ID in the query.
// Returns a *NotSingularError when more than one Roles ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *RolesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roles.Label}
	default:
		err = &NotSingularError{roles.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *RolesQuery) OnlyIDX(ctx context.Context) int {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RolesSlice.
func (rq *RolesQuery) All(ctx context.Context) ([]*Roles, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Roles, *RolesQuery]()
	return withInterceptors[[]*Roles](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *RolesQuery) AllX(ctx context.Context) []*Roles {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Roles IDs.
func (rq *RolesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err = rq.Select(roles.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *RolesQuery) IDsX(ctx context.Context) []int {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *RolesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*RolesQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *RolesQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *RolesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *RolesQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RolesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *RolesQuery) Clone() *RolesQuery {
	if rq == nil {
		return nil
	}
	return &RolesQuery{
		config:              rq.config,
		ctx:                 rq.ctx.Clone(),
		order:               append([]roles.OrderOption{}, rq.order...),
		inters:              append([]Interceptor{}, rq.inters...),
		predicates:          append([]predicate.Roles{}, rq.predicates...),
		withUserRoles:       rq.withUserRoles.Clone(),
		withRolePermissions: rq.withRolePermissions.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithUserRoles tells the query-builder to eager-load the nodes that are connected to
// the "user_roles" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RolesQuery) WithUserRoles(opts ...func(*UserRolesQuery)) *RolesQuery {
	query := (&UserRolesClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withUserRoles = query
	return rq
}

// WithRolePermissions tells the query-builder to eager-load the nodes that are connected to
// the "role_permissions" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RolesQuery) WithRolePermissions(opts ...func(*RolePermissionsQuery)) *RolesQuery {
	query := (&RolePermissionsClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withRolePermissions = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Roles.Query().
//		GroupBy(roles.FieldCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *RolesQuery) GroupBy(field string, fields ...string) *RolesGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RolesGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = roles.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//	}
//
//	client.Roles.Query().
//		Select(roles.FieldCode).
//		Scan(ctx, &v)
func (rq *RolesQuery) Select(fields ...string) *RolesSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &RolesSelect{RolesQuery: rq}
	sbuild.label = roles.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RolesSelect configured with the given aggregations.
func (rq *RolesQuery) Aggregate(fns ...AggregateFunc) *RolesSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *RolesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !roles.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *RolesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Roles, error) {
	var (
		nodes       = []*Roles{}
		_spec       = rq.querySpec()
		loadedTypes = [2]bool{
			rq.withUserRoles != nil,
			rq.withRolePermissions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Roles).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Roles{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withUserRoles; query != nil {
		if err := rq.loadUserRoles(ctx, query, nodes,
			func(n *Roles) { n.Edges.UserRoles = []*UserRoles{} },
			func(n *Roles, e *UserRoles) { n.Edges.UserRoles = append(n.Edges.UserRoles, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withRolePermissions; query != nil {
		if err := rq.loadRolePermissions(ctx, query, nodes,
			func(n *Roles) { n.Edges.RolePermissions = []*RolePermissions{} },
			func(n *Roles, e *RolePermissions) { n.Edges.RolePermissions = append(n.Edges.RolePermissions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *RolesQuery) loadUserRoles(ctx context.Context, query *UserRolesQuery, nodes []*Roles, init func(*Roles), assign func(*Roles, *UserRoles)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Roles)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(userroles.FieldRoleID)
	}
	query.Where(predicate.UserRoles(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(roles.UserRolesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RoleID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "role_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (rq *RolesQuery) loadRolePermissions(ctx context.Context, query *RolePermissionsQuery, nodes []*Roles, init func(*Roles), assign func(*Roles, *RolePermissions)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Roles)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rolepermissions.FieldRoleID)
	}
	query.Where(predicate.RolePermissions(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(roles.RolePermissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RoleID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "role_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rq *RolesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *RolesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roles.Table, roles.Columns, sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roles.FieldID)
		for i := range fields {
			if fields[i] != roles.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *RolesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(roles.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = roles.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RolesGroupBy is the group-by builder for Roles entities.
type RolesGroupBy struct {
	selector
	build *RolesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *RolesGroupBy) Aggregate(fns ...AggregateFunc) *RolesGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *RolesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RolesQuery, *RolesGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *RolesGroupBy) sqlScan(ctx context.Context, root *RolesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RolesSelect is the builder for selecting fields of Roles entities.
type RolesSelect struct {
	*RolesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *RolesSelect) Aggregate(fns ...AggregateFunc) *RolesSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *RolesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RolesQuery, *RolesSelect](ctx, rs.RolesQuery, rs, rs.inters, v)
}

func (rs *RolesSelect) sqlScan(ctx context.Context, root *RolesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
