// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shammianand/go-auth/ent/roles"
)

// Roles is the model entity for the Roles schema.
type Roles struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RolesQuery when eager-loading is set.
	Edges        RolesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RolesEdges holds the relations/edges for other nodes in the graph.
type RolesEdges struct {
	// Users holds the value of the users edge.
	Users []*Users `json:"users,omitempty"`
	// Permissions holds the value of the permissions edge.
	Permissions []*Permissions `json:"permissions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e RolesEdges) UsersOrErr() ([]*Users, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e RolesEdges) PermissionsOrErr() ([]*Permissions, error) {
	if e.loadedTypes[1] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Roles) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case roles.FieldID:
			values[i] = new(sql.NullInt64)
		case roles.FieldName, roles.FieldDescription:
			values[i] = new(sql.NullString)
		case roles.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Roles fields.
func (r *Roles) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case roles.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case roles.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				r.Name = value.String
			}
		case roles.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				r.Description = value.String
			}
		case roles.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Roles.
// This includes values selected through modifiers, order, etc.
func (r *Roles) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Roles entity.
func (r *Roles) QueryUsers() *UsersQuery {
	return NewRolesClient(r.config).QueryUsers(r)
}

// QueryPermissions queries the "permissions" edge of the Roles entity.
func (r *Roles) QueryPermissions() *PermissionsQuery {
	return NewRolesClient(r.config).QueryPermissions(r)
}

// Update returns a builder for updating this Roles.
// Note that you need to call Roles.Unwrap() before calling this method if this Roles
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Roles) Update() *RolesUpdateOne {
	return NewRolesClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Roles entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Roles) Unwrap() *Roles {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Roles is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Roles) String() string {
	var builder strings.Builder
	builder.WriteString("Roles(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("name=")
	builder.WriteString(r.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(r.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RolesSlice is a parsable slice of Roles.
type RolesSlice []*Roles
