// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shammianand/go-auth/ent/predicate"
	"github.com/shammianand/go-auth/ent/rolepermissions"
	"github.com/shammianand/go-auth/ent/roles"
	"github.com/shammianand/go-auth/ent/userroles"
)

// RolesUpdate is the builder for updating Roles entities.
type RolesUpdate struct {
	config
	hooks    []Hook
	mutation *RolesMutation
}

// Where appends a list predicates to the RolesUpdate builder.
func (ru *RolesUpdate) Where(ps ...predicate.Roles) *RolesUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetCode sets the "code" field.
func (ru *RolesUpdate) SetCode(s string) *RolesUpdate {
	ru.mutation.SetCode(s)
	return ru
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (ru *RolesUpdate) SetNillableCode(s *string) *RolesUpdate {
	if s != nil {
		ru.SetCode(*s)
	}
	return ru
}

// SetName sets the "name" field.
func (ru *RolesUpdate) SetName(s string) *RolesUpdate {
	ru.mutation.SetName(s)
	return ru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ru *RolesUpdate) SetNillableName(s *string) *RolesUpdate {
	if s != nil {
		ru.SetName(*s)
	}
	return ru
}

// SetDescription sets the "description" field.
func (ru *RolesUpdate) SetDescription(s string) *RolesUpdate {
	ru.mutation.SetDescription(s)
	return ru
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ru *RolesUpdate) SetNillableDescription(s *string) *RolesUpdate {
	if s != nil {
		ru.SetDescription(*s)
	}
	return ru
}

// ClearDescription clears the value of the "description" field.
func (ru *RolesUpdate) ClearDescription() *RolesUpdate {
	ru.mutation.ClearDescription()
	return ru
}

// SetIsSystem sets the "is_system" field.
func (ru *RolesUpdate) SetIsSystem(b bool) *RolesUpdate {
	ru.mutation.SetIsSystem(b)
	return ru
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (ru *RolesUpdate) SetNillableIsSystem(b *bool) *RolesUpdate {
	if b != nil {
		ru.SetIsSystem(*b)
	}
	return ru
}

// SetIsDefault sets the "is_default" field.
func (ru *RolesUpdate) SetIsDefault(b bool) *RolesUpdate {
	ru.mutation.SetIsDefault(b)
	return ru
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (ru *RolesUpdate) SetNillableIsDefault(b *bool) *RolesUpdate {
	if b != nil {
		ru.SetIsDefault(*b)
	}
	return ru
}

// SetMaxUsers sets the "max_users" field.
func (ru *RolesUpdate) SetMaxUsers(i int) *RolesUpdate {
	ru.mutation.ResetMaxUsers()
	ru.mutation.SetMaxUsers(i)
	return ru
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (ru *RolesUpdate) SetNillableMaxUsers(i *int) *RolesUpdate {
	if i != nil {
		ru.SetMaxUsers(*i)
	}
	return ru
}

// AddMaxUsers adds i to the "max_users" field.
func (ru *RolesUpdate) AddMaxUsers(i int) *RolesUpdate {
	ru.mutation.AddMaxUsers(i)
	return ru
}

// ClearMaxUsers clears the value of the "max_users" field.
func (ru *RolesUpdate) ClearMaxUsers() *RolesUpdate {
	ru.mutation.ClearMaxUsers()
	return ru
}

// SetUpdatedAt sets the "updated_at" field.
func (ru *RolesUpdate) SetUpdatedAt(t time.Time) *RolesUpdate {
	ru.mutation.SetUpdatedAt(t)
	return ru
}

// AddUserRoleIDs adds the "user_roles" edge to the UserRoles entity by IDs.
func (ru *RolesUpdate) AddUserRoleIDs(ids ...uuid.UUID) *RolesUpdate {
	ru.mutation.AddUserRoleIDs(ids...)
	return ru
}

// AddUserRoles adds the "user_roles" edges to the UserRoles entity.
func (ru *RolesUpdate) AddUserRoles(u ...*UserRoles) *RolesUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ru.AddUserRoleIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermissions entity by IDs.
func (ru *RolesUpdate) AddRolePermissionIDs(ids ...int) *RolesUpdate {
	ru.mutation.AddRolePermissionIDs(ids...)
	return ru
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermissions entity.
func (ru *RolesUpdate) AddRolePermissions(r ...*RolePermissions) *RolesUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddRolePermissionIDs(ids...)
}

// Mutation returns the RolesMutation object of the builder.
func (ru *RolesUpdate) Mutation() *RolesMutation {
	return ru.mutation
}

// ClearUserRoles clears all "user_roles" edges to the UserRoles entity.
func (ru *RolesUpdate) ClearUserRoles() *RolesUpdate {
	ru.mutation.ClearUserRoles()
	return ru
}

// RemoveUserRoleIDs removes the "user_roles" edge to UserRoles entities by IDs.
func (ru *RolesUpdate) RemoveUserRoleIDs(ids ...uuid.UUID) *RolesUpdate {
	ru.mutation.RemoveUserRoleIDs(ids...)
	return ru
}

// RemoveUserRoles removes "user_roles" edges to UserRoles entities.
func (ru *RolesUpdate) RemoveUserRoles(u ...*UserRoles) *RolesUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ru.RemoveUserRoleIDs(ids...)
}

// ClearRolePermissions clears all "role_permissions" edges to the RolePermissions entity.
func (ru *RolesUpdate) ClearRolePermissions() *RolesUpdate {
	ru.mutation.ClearRolePermissions()
	return ru
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RolePermissions entities by IDs.
func (ru *RolesUpdate) RemoveRolePermissionIDs(ids ...int) *RolesUpdate {
	ru.mutation.RemoveRolePermissionIDs(ids...)
	return ru
}

// RemoveRolePermissions removes "role_permissions" edges to RolePermissions entities.
func (ru *RolesUpdate) RemoveRolePermissions(r ...*RolePermissions) *RolesUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveRolePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RolesUpdate) Save(ctx context.Context) (int, error) {
	ru.defaults()
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RolesUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RolesUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RolesUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *RolesUpdate) defaults() {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		v := roles.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RolesUpdate) check() error {
	if v, ok := ru.mutation.Code(); ok {
		if err := roles.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Roles.code": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Name(); ok {
		if err := roles.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Roles.name": %w`, err)}
		}
	}
	return nil
}

func (ru *RolesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(roles.Table, roles.Columns, sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Code(); ok {
		_spec.SetField(roles.FieldCode, field.TypeString, value)
	}
	if value, ok := ru.mutation.Name(); ok {
		_spec.SetField(roles.FieldName, field.TypeString, value)
	}
	if value, ok := ru.mutation.Description(); ok {
		_spec.SetField(roles.FieldDescription, field.TypeString, value)
	}
	if ru.mutation.DescriptionCleared() {
		_spec.ClearField(roles.FieldDescription, field.TypeString)
	}
	if value, ok := ru.mutation.IsSystem(); ok {
		_spec.SetField(roles.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := ru.mutation.IsDefault(); ok {
		_spec.SetField(roles.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := ru.mutation.MaxUsers(); ok {
		_spec.SetField(roles.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedMaxUsers(); ok {
		_spec.AddField(roles.FieldMaxUsers, field.TypeInt, value)
	}
	if ru.mutation.MaxUsersCleared() {
		_spec.ClearField(roles.FieldMaxUsers, field.TypeInt)
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.SetField(roles.FieldUpdatedAt, field.TypeTime, value)
	}
	if ru.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.UserRolesTable,
			Columns: []string{roles.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroles.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !ru.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.UserRolesTable,
			Columns: []string{roles.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.UserRolesTable,
			Columns: []string{roles.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.RolePermissionsTable,
			Columns: []string{roles.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !ru.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.RolePermissionsTable,
			Columns: []string{roles.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.RolePermissionsTable,
			Columns: []string{roles.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roles.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RolesUpdateOne is the builder for updating a single Roles entity.
type RolesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RolesMutation
}

// SetCode sets the "code" field.
func (ruo *RolesUpdateOne) SetCode(s string) *RolesUpdateOne {
	ruo.mutation.SetCode(s)
	return ruo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (ruo *RolesUpdateOne) SetNillableCode(s *string) *RolesUpdateOne {
	if s != nil {
		ruo.SetCode(*s)
	}
	return ruo
}

// SetName sets the "name" field.
func (ruo *RolesUpdateOne) SetName(s string) *RolesUpdateOne {
	ruo.mutation.SetName(s)
	return ruo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ruo *RolesUpdateOne) SetNillableName(s *string) *RolesUpdateOne {
	if s != nil {
		ruo.SetName(*s)
	}
	return ruo
}

// SetDescription sets the "description" field.
func (ruo *RolesUpdateOne) SetDescription(s string) *RolesUpdateOne {
	ruo.mutation.SetDescription(s)
	return ruo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ruo *RolesUpdateOne) SetNillableDescription(s *string) *RolesUpdateOne {
	if s != nil {
		ruo.SetDescription(*s)
	}
	return ruo
}

// ClearDescription clears the value of the "description" field.
func (ruo *RolesUpdateOne) ClearDescription() *RolesUpdateOne {
	ruo.mutation.ClearDescription()
	return ruo
}

// SetIsSystem sets the "is_system" field.
func (ruo *RolesUpdateOne) SetIsSystem(b bool) *RolesUpdateOne {
	ruo.mutation.SetIsSystem(b)
	return ruo
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (ruo *RolesUpdateOne) SetNillableIsSystem(b *bool) *RolesUpdateOne {
	if b != nil {
		ruo.SetIsSystem(*b)
	}
	return ruo
}

// SetIsDefault sets the "is_default" field.
func (ruo *RolesUpdateOne) SetIsDefault(b bool) *RolesUpdateOne {
	ruo.mutation.SetIsDefault(b)
	return ruo
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (ruo *RolesUpdateOne) SetNillableIsDefault(b *bool) *RolesUpdateOne {
	if b != nil {
		ruo.SetIsDefault(*b)
	}
	return ruo
}

// SetMaxUsers sets the "max_users" field.
func (ruo *RolesUpdateOne) SetMaxUsers(i int) *RolesUpdateOne {
	ruo.mutation.ResetMaxUsers()
	ruo.mutation.SetMaxUsers(i)
	return ruo
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (ruo *RolesUpdateOne) SetNillableMaxUsers(i *int) *RolesUpdateOne {
	if i != nil {
		ruo.SetMaxUsers(*i)
	}
	return ruo
}

// AddMaxUsers adds i to the "max_users" field.
func (ruo *RolesUpdateOne) AddMaxUsers(i int) *RolesUpdateOne {
	ruo.mutation.AddMaxUsers(i)
	return ruo
}

// ClearMaxUsers clears the value of the "max_users" field.
func (ruo *RolesUpdateOne) ClearMaxUsers() *RolesUpdateOne {
	ruo.mutation.ClearMaxUsers()
	return ruo
}

// SetUpdatedAt sets the "updated_at" field.
func (ruo *RolesUpdateOne) SetUpdatedAt(t time.Time) *RolesUpdateOne {
	ruo.mutation.SetUpdatedAt(t)
	return ruo
}

// AddUserRoleIDs adds the "user_roles" edge to the UserRoles entity by IDs.
func (ruo *RolesUpdateOne) AddUserRoleIDs(ids ...uuid.UUID) *RolesUpdateOne {
	ruo.mutation.AddUserRoleIDs(ids...)
	return ruo
}

// AddUserRoles adds the "user_roles" edges to the UserRoles entity.
func (ruo *RolesUpdateOne) AddUserRoles(u ...*UserRoles) *RolesUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ruo.AddUserRoleIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermissions entity by IDs.
func (ruo *RolesUpdateOne) AddRolePermissionIDs(ids ...int) *RolesUpdateOne {
	ruo.mutation.AddRolePermissionIDs(ids...)
	return ruo
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermissions entity.
func (ruo *RolesUpdateOne) AddRolePermissions(r ...*RolePermissions) *RolesUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddRolePermissionIDs(ids...)
}

// Mutation returns the RolesMutation object of the builder.
func (ruo *RolesUpdateOne) Mutation() *RolesMutation {
	return ruo.mutation
}

// ClearUserRoles clears all "user_roles" edges to the UserRoles entity.
func (ruo *RolesUpdateOne) ClearUserRoles() *RolesUpdateOne {
	ruo.mutation.ClearUserRoles()
	return ruo
}

// RemoveUserRoleIDs removes the "user_roles" edge to UserRoles entities by IDs.
func (ruo *RolesUpdateOne) RemoveUserRoleIDs(ids ...uuid.UUID) *RolesUpdateOne {
	ruo.mutation.RemoveUserRoleIDs(ids...)
	return ruo
}

// RemoveUserRoles removes "user_roles" edges to UserRoles entities.
func (ruo *RolesUpdateOne) RemoveUserRoles(u ...*UserRoles) *RolesUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ruo.RemoveUserRoleIDs(ids...)
}

// ClearRolePermissions clears all "role_permissions" edges to the RolePermissions entity.
func (ruo *RolesUpdateOne) ClearRolePermissions() *RolesUpdateOne {
	ruo.mutation.ClearRolePermissions()
	return ruo
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RolePermissions entities by IDs.
func (ruo *RolesUpdateOne) RemoveRolePermissionIDs(ids ...int) *RolesUpdateOne {
	ruo.mutation.RemoveRolePermissionIDs(ids...)
	return ruo
}

// RemoveRolePermissions removes "role_permissions" edges to RolePermissions entities.
func (ruo *RolesUpdateOne) RemoveRolePermissions(r ...*RolePermissions) *RolesUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveRolePermissionIDs(ids...)
}

// Where appends a list predicates to the RolesUpdate builder.
func (ruo *RolesUpdateOne) Where(ps ...predicate.Roles) *RolesUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RolesUpdateOne) Select(field string, fields ...string) *RolesUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Roles entity.
func (ruo *RolesUpdateOne) Save(ctx context.Context) (*Roles, error) {
	ruo.defaults()
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RolesUpdateOne) SaveX(ctx context.Context) *Roles {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RolesUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RolesUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *RolesUpdateOne) defaults() {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		v := roles.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RolesUpdateOne) check() error {
	if v, ok := ruo.mutation.Code(); ok {
		if err := roles.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Roles.code": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Name(); ok {
		if err := roles.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Roles.name": %w`, err)}
		}
	}
	return nil
}

func (ruo *RolesUpdateOne) sqlSave(ctx context.Context) (_node *Roles, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(roles.Table, roles.Columns, sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Roles.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roles.FieldID)
		for _, f := range fields {
			if !roles.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != roles.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Code(); ok {
		_spec.SetField(roles.FieldCode, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Name(); ok {
		_spec.SetField(roles.FieldName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Description(); ok {
		_spec.SetField(roles.FieldDescription, field.TypeString, value)
	}
	if ruo.mutation.DescriptionCleared() {
		_spec.ClearField(roles.FieldDescription, field.TypeString)
	}
	if value, ok := ruo.mutation.IsSystem(); ok {
		_spec.SetField(roles.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := ruo.mutation.IsDefault(); ok {
		_spec.SetField(roles.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := ruo.mutation.MaxUsers(); ok {
		_spec.SetField(roles.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedMaxUsers(); ok {
		_spec.AddField(roles.FieldMaxUsers, field.TypeInt, value)
	}
	if ruo.mutation.MaxUsersCleared() {
		_spec.ClearField(roles.FieldMaxUsers, field.TypeInt)
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.SetField(roles.FieldUpdatedAt, field.TypeTime, value)
	}
	if ruo.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.UserRolesTable,
			Columns: []string{roles.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroles.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !ruo.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.UserRolesTable,
			Columns: []string{roles.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.UserRolesTable,
			Columns: []string{roles.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.RolePermissionsTable,
			Columns: []string{roles.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !ruo.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.RolePermissionsTable,
			Columns: []string{roles.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   roles.RolePermissionsTable,
			Columns: []string{roles.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Roles{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roles.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
