// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shammianand/go-auth/ent/permissions"
	"github.com/shammianand/go-auth/ent/predicate"
	"github.com/shammianand/go-auth/ent/rolepermissions"
	"github.com/shammianand/go-auth/ent/roles"
)

// RolePermissionsUpdate is the builder for updating RolePermissions entities.
type RolePermissionsUpdate struct {
	config
	hooks    []Hook
	mutation *RolePermissionsMutation
}

// Where appends a list predicates to the RolePermissionsUpdate builder.
func (rpu *RolePermissionsUpdate) Where(ps ...predicate.RolePermissions) *RolePermissionsUpdate {
	rpu.mutation.Where(ps...)
	return rpu
}

// SetRoleID sets the "role_id" field.
func (rpu *RolePermissionsUpdate) SetRoleID(i int) *RolePermissionsUpdate {
	rpu.mutation.SetRoleID(i)
	return rpu
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (rpu *RolePermissionsUpdate) SetNillableRoleID(i *int) *RolePermissionsUpdate {
	if i != nil {
		rpu.SetRoleID(*i)
	}
	return rpu
}

// SetPermissionID sets the "permission_id" field.
func (rpu *RolePermissionsUpdate) SetPermissionID(i int) *RolePermissionsUpdate {
	rpu.mutation.SetPermissionID(i)
	return rpu
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (rpu *RolePermissionsUpdate) SetNillablePermissionID(i *int) *RolePermissionsUpdate {
	if i != nil {
		rpu.SetPermissionID(*i)
	}
	return rpu
}

// SetRole sets the "role" edge to the Roles entity.
func (rpu *RolePermissionsUpdate) SetRole(r *Roles) *RolePermissionsUpdate {
	return rpu.SetRoleID(r.ID)
}

// SetPermission sets the "permission" edge to the Permissions entity.
func (rpu *RolePermissionsUpdate) SetPermission(p *Permissions) *RolePermissionsUpdate {
	return rpu.SetPermissionID(p.ID)
}

// Mutation returns the RolePermissionsMutation object of the builder.
func (rpu *RolePermissionsUpdate) Mutation() *RolePermissionsMutation {
	return rpu.mutation
}

// ClearRole clears the "role" edge to the Roles entity.
func (rpu *RolePermissionsUpdate) ClearRole() *RolePermissionsUpdate {
	rpu.mutation.ClearRole()
	return rpu
}

// ClearPermission clears the "permission" edge to the Permissions entity.
func (rpu *RolePermissionsUpdate) ClearPermission() *RolePermissionsUpdate {
	rpu.mutation.ClearPermission()
	return rpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rpu *RolePermissionsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rpu.sqlSave, rpu.mutation, rpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rpu *RolePermissionsUpdate) SaveX(ctx context.Context) int {
	affected, err := rpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rpu *RolePermissionsUpdate) Exec(ctx context.Context) error {
	_, err := rpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpu *RolePermissionsUpdate) ExecX(ctx context.Context) {
	if err := rpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpu *RolePermissionsUpdate) check() error {
	if _, ok := rpu.mutation.RoleID(); rpu.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "RolePermissions.role"`)
	}
	if _, ok := rpu.mutation.PermissionID(); rpu.mutation.PermissionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "RolePermissions.permission"`)
	}
	return nil
}

func (rpu *RolePermissionsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepermissions.Table, rolepermissions.Columns, sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt))
	if ps := rpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if rpu.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermissions.RoleTable,
			Columns: []string{rolepermissions.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpu.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermissions.RoleTable,
			Columns: []string{rolepermissions.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rpu.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermissions.PermissionTable,
			Columns: []string{rolepermissions.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpu.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermissions.PermissionTable,
			Columns: []string{rolepermissions.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepermissions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rpu.mutation.done = true
	return n, nil
}

// RolePermissionsUpdateOne is the builder for updating a single RolePermissions entity.
type RolePermissionsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RolePermissionsMutation
}

// SetRoleID sets the "role_id" field.
func (rpuo *RolePermissionsUpdateOne) SetRoleID(i int) *RolePermissionsUpdateOne {
	rpuo.mutation.SetRoleID(i)
	return rpuo
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (rpuo *RolePermissionsUpdateOne) SetNillableRoleID(i *int) *RolePermissionsUpdateOne {
	if i != nil {
		rpuo.SetRoleID(*i)
	}
	return rpuo
}

// SetPermissionID sets the "permission_id" field.
func (rpuo *RolePermissionsUpdateOne) SetPermissionID(i int) *RolePermissionsUpdateOne {
	rpuo.mutation.SetPermissionID(i)
	return rpuo
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (rpuo *RolePermissionsUpdateOne) SetNillablePermissionID(i *int) *RolePermissionsUpdateOne {
	if i != nil {
		rpuo.SetPermissionID(*i)
	}
	return rpuo
}

// SetRole sets the "role" edge to the Roles entity.
func (rpuo *RolePermissionsUpdateOne) SetRole(r *Roles) *RolePermissionsUpdateOne {
	return rpuo.SetRoleID(r.ID)
}

// SetPermission sets the "permission" edge to the Permissions entity.
func (rpuo *RolePermissionsUpdateOne) SetPermission(p *Permissions) *RolePermissionsUpdateOne {
	return rpuo.SetPermissionID(p.ID)
}

// Mutation returns the RolePermissionsMutation object of the builder.
func (rpuo *RolePermissionsUpdateOne) Mutation() *RolePermissionsMutation {
	return rpuo.mutation
}

// ClearRole clears the "role" edge to the Roles entity.
func (rpuo *RolePermissionsUpdateOne) ClearRole() *RolePermissionsUpdateOne {
	rpuo.mutation.ClearRole()
	return rpuo
}

// ClearPermission clears the "permission" edge to the Permissions entity.
func (rpuo *RolePermissionsUpdateOne) ClearPermission() *RolePermissionsUpdateOne {
	rpuo.mutation.ClearPermission()
	return rpuo
}

// Where appends a list predicates to the RolePermissionsUpdate builder.
func (rpuo *RolePermissionsUpdateOne) Where(ps ...predicate.RolePermissions) *RolePermissionsUpdateOne {
	rpuo.mutation.Where(ps...)
	return rpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rpuo *RolePermissionsUpdateOne) Select(field string, fields ...string) *RolePermissionsUpdateOne {
	rpuo.fields = append([]string{field}, fields...)
	return rpuo
}

// Save executes the query and returns the updated RolePermissions entity.
func (rpuo *RolePermissionsUpdateOne) Save(ctx context.Context) (*RolePermissions, error) {
	return withHooks(ctx, rpuo.sqlSave, rpuo.mutation, rpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rpuo *RolePermissionsUpdateOne) SaveX(ctx context.Context) *RolePermissions {
	node, err := rpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rpuo *RolePermissionsUpdateOne) Exec(ctx context.Context) error {
	_, err := rpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpuo *RolePermissionsUpdateOne) ExecX(ctx context.Context) {
	if err := rpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpuo *RolePermissionsUpdateOne) check() error {
	if _, ok := rpuo.mutation.RoleID(); rpuo.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "RolePermissions.role"`)
	}
	if _, ok := rpuo.mutation.PermissionID(); rpuo.mutation.PermissionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "RolePermissions.permission"`)
	}
	return nil
}

func (rpuo *RolePermissionsUpdateOne) sqlSave(ctx context.Context) (_node *RolePermissions, err error) {
	if err := rpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepermissions.Table, rolepermissions.Columns, sqlgraph.NewFieldSpec(rolepermissions.FieldID, field.TypeInt))
	id, ok := rpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RolePermissions.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rolepermissions.FieldID)
		for _, f := range fields {
			if !rolepermissions.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rolepermissions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if rpuo.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermissions.RoleTable,
			Columns: []string{rolepermissions.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpuo.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermissions.RoleTable,
			Columns: []string{rolepermissions.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rpuo.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermissions.PermissionTable,
			Columns: []string{rolepermissions.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpuo.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermissions.PermissionTable,
			Columns: []string{rolepermissions.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RolePermissions{config: rpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepermissions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rpuo.mutation.done = true
	return _node, nil
}
