// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shammianand/go-auth/ent/predicate"
	"github.com/shammianand/go-auth/ent/roles"
	"github.com/shammianand/go-auth/ent/users"
)

// UsersUpdate is the builder for updating Users entities.
type UsersUpdate struct {
	config
	hooks    []Hook
	mutation *UsersMutation
}

// Where appends a list predicates to the UsersUpdate builder.
func (uu *UsersUpdate) Where(ps ...predicate.Users) *UsersUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetEmail sets the "email" field.
func (uu *UsersUpdate) SetEmail(s string) *UsersUpdate {
	uu.mutation.SetEmail(s)
	return uu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableEmail(s *string) *UsersUpdate {
	if s != nil {
		uu.SetEmail(*s)
	}
	return uu
}

// SetPasswordHash sets the "password_hash" field.
func (uu *UsersUpdate) SetPasswordHash(s string) *UsersUpdate {
	uu.mutation.SetPasswordHash(s)
	return uu
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (uu *UsersUpdate) SetNillablePasswordHash(s *string) *UsersUpdate {
	if s != nil {
		uu.SetPasswordHash(*s)
	}
	return uu
}

// SetCreatedAt sets the "created_at" field.
func (uu *UsersUpdate) SetCreatedAt(t time.Time) *UsersUpdate {
	uu.mutation.SetCreatedAt(t)
	return uu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableCreatedAt(t *time.Time) *UsersUpdate {
	if t != nil {
		uu.SetCreatedAt(*t)
	}
	return uu
}

// SetUpdatedAt sets the "updated_at" field.
func (uu *UsersUpdate) SetUpdatedAt(t time.Time) *UsersUpdate {
	uu.mutation.SetUpdatedAt(t)
	return uu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableUpdatedAt(t *time.Time) *UsersUpdate {
	if t != nil {
		uu.SetUpdatedAt(*t)
	}
	return uu
}

// SetLastLogin sets the "last_login" field.
func (uu *UsersUpdate) SetLastLogin(t time.Time) *UsersUpdate {
	uu.mutation.SetLastLogin(t)
	return uu
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableLastLogin(t *time.Time) *UsersUpdate {
	if t != nil {
		uu.SetLastLogin(*t)
	}
	return uu
}

// ClearLastLogin clears the value of the "last_login" field.
func (uu *UsersUpdate) ClearLastLogin() *UsersUpdate {
	uu.mutation.ClearLastLogin()
	return uu
}

// SetIsActive sets the "is_active" field.
func (uu *UsersUpdate) SetIsActive(b bool) *UsersUpdate {
	uu.mutation.SetIsActive(b)
	return uu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableIsActive(b *bool) *UsersUpdate {
	if b != nil {
		uu.SetIsActive(*b)
	}
	return uu
}

// SetEmailVerified sets the "email_verified" field.
func (uu *UsersUpdate) SetEmailVerified(b bool) *UsersUpdate {
	uu.mutation.SetEmailVerified(b)
	return uu
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableEmailVerified(b *bool) *UsersUpdate {
	if b != nil {
		uu.SetEmailVerified(*b)
	}
	return uu
}

// SetVerificationToken sets the "verification_token" field.
func (uu *UsersUpdate) SetVerificationToken(s string) *UsersUpdate {
	uu.mutation.SetVerificationToken(s)
	return uu
}

// SetNillableVerificationToken sets the "verification_token" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableVerificationToken(s *string) *UsersUpdate {
	if s != nil {
		uu.SetVerificationToken(*s)
	}
	return uu
}

// ClearVerificationToken clears the value of the "verification_token" field.
func (uu *UsersUpdate) ClearVerificationToken() *UsersUpdate {
	uu.mutation.ClearVerificationToken()
	return uu
}

// SetVerificationTokenExpiry sets the "verification_token_expiry" field.
func (uu *UsersUpdate) SetVerificationTokenExpiry(t time.Time) *UsersUpdate {
	uu.mutation.SetVerificationTokenExpiry(t)
	return uu
}

// SetNillableVerificationTokenExpiry sets the "verification_token_expiry" field if the given value is not nil.
func (uu *UsersUpdate) SetNillableVerificationTokenExpiry(t *time.Time) *UsersUpdate {
	if t != nil {
		uu.SetVerificationTokenExpiry(*t)
	}
	return uu
}

// ClearVerificationTokenExpiry clears the value of the "verification_token_expiry" field.
func (uu *UsersUpdate) ClearVerificationTokenExpiry() *UsersUpdate {
	uu.mutation.ClearVerificationTokenExpiry()
	return uu
}

// SetPasswordResetToken sets the "password_reset_token" field.
func (uu *UsersUpdate) SetPasswordResetToken(s string) *UsersUpdate {
	uu.mutation.SetPasswordResetToken(s)
	return uu
}

// SetNillablePasswordResetToken sets the "password_reset_token" field if the given value is not nil.
func (uu *UsersUpdate) SetNillablePasswordResetToken(s *string) *UsersUpdate {
	if s != nil {
		uu.SetPasswordResetToken(*s)
	}
	return uu
}

// ClearPasswordResetToken clears the value of the "password_reset_token" field.
func (uu *UsersUpdate) ClearPasswordResetToken() *UsersUpdate {
	uu.mutation.ClearPasswordResetToken()
	return uu
}

// SetPasswordResetTokenExpiry sets the "password_reset_token_expiry" field.
func (uu *UsersUpdate) SetPasswordResetTokenExpiry(t time.Time) *UsersUpdate {
	uu.mutation.SetPasswordResetTokenExpiry(t)
	return uu
}

// SetNillablePasswordResetTokenExpiry sets the "password_reset_token_expiry" field if the given value is not nil.
func (uu *UsersUpdate) SetNillablePasswordResetTokenExpiry(t *time.Time) *UsersUpdate {
	if t != nil {
		uu.SetPasswordResetTokenExpiry(*t)
	}
	return uu
}

// ClearPasswordResetTokenExpiry clears the value of the "password_reset_token_expiry" field.
func (uu *UsersUpdate) ClearPasswordResetTokenExpiry() *UsersUpdate {
	uu.mutation.ClearPasswordResetTokenExpiry()
	return uu
}

// SetMetadata sets the "metadata" field.
func (uu *UsersUpdate) SetMetadata(m map[string]interface{}) *UsersUpdate {
	uu.mutation.SetMetadata(m)
	return uu
}

// ClearMetadata clears the value of the "metadata" field.
func (uu *UsersUpdate) ClearMetadata() *UsersUpdate {
	uu.mutation.ClearMetadata()
	return uu
}

// AddRoleIDs adds the "roles" edge to the Roles entity by IDs.
func (uu *UsersUpdate) AddRoleIDs(ids ...int) *UsersUpdate {
	uu.mutation.AddRoleIDs(ids...)
	return uu
}

// AddRoles adds the "roles" edges to the Roles entity.
func (uu *UsersUpdate) AddRoles(r ...*Roles) *UsersUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uu.AddRoleIDs(ids...)
}

// Mutation returns the UsersMutation object of the builder.
func (uu *UsersUpdate) Mutation() *UsersMutation {
	return uu.mutation
}

// ClearRoles clears all "roles" edges to the Roles entity.
func (uu *UsersUpdate) ClearRoles() *UsersUpdate {
	uu.mutation.ClearRoles()
	return uu
}

// RemoveRoleIDs removes the "roles" edge to Roles entities by IDs.
func (uu *UsersUpdate) RemoveRoleIDs(ids ...int) *UsersUpdate {
	uu.mutation.RemoveRoleIDs(ids...)
	return uu
}

// RemoveRoles removes "roles" edges to Roles entities.
func (uu *UsersUpdate) RemoveRoles(r ...*Roles) *UsersUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uu.RemoveRoleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UsersUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UsersUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UsersUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UsersUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UsersUpdate) check() error {
	if v, ok := uu.mutation.Email(); ok {
		if err := users.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Users.email": %w`, err)}
		}
	}
	if v, ok := uu.mutation.PasswordHash(); ok {
		if err := users.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Users.password_hash": %w`, err)}
		}
	}
	return nil
}

func (uu *UsersUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(users.Table, users.Columns, sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Email(); ok {
		_spec.SetField(users.FieldEmail, field.TypeString, value)
	}
	if value, ok := uu.mutation.PasswordHash(); ok {
		_spec.SetField(users.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := uu.mutation.CreatedAt(); ok {
		_spec.SetField(users.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.UpdatedAt(); ok {
		_spec.SetField(users.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.LastLogin(); ok {
		_spec.SetField(users.FieldLastLogin, field.TypeTime, value)
	}
	if uu.mutation.LastLoginCleared() {
		_spec.ClearField(users.FieldLastLogin, field.TypeTime)
	}
	if value, ok := uu.mutation.IsActive(); ok {
		_spec.SetField(users.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := uu.mutation.EmailVerified(); ok {
		_spec.SetField(users.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := uu.mutation.VerificationToken(); ok {
		_spec.SetField(users.FieldVerificationToken, field.TypeString, value)
	}
	if uu.mutation.VerificationTokenCleared() {
		_spec.ClearField(users.FieldVerificationToken, field.TypeString)
	}
	if value, ok := uu.mutation.VerificationTokenExpiry(); ok {
		_spec.SetField(users.FieldVerificationTokenExpiry, field.TypeTime, value)
	}
	if uu.mutation.VerificationTokenExpiryCleared() {
		_spec.ClearField(users.FieldVerificationTokenExpiry, field.TypeTime)
	}
	if value, ok := uu.mutation.PasswordResetToken(); ok {
		_spec.SetField(users.FieldPasswordResetToken, field.TypeString, value)
	}
	if uu.mutation.PasswordResetTokenCleared() {
		_spec.ClearField(users.FieldPasswordResetToken, field.TypeString)
	}
	if value, ok := uu.mutation.PasswordResetTokenExpiry(); ok {
		_spec.SetField(users.FieldPasswordResetTokenExpiry, field.TypeTime, value)
	}
	if uu.mutation.PasswordResetTokenExpiryCleared() {
		_spec.ClearField(users.FieldPasswordResetTokenExpiry, field.TypeTime)
	}
	if value, ok := uu.mutation.Metadata(); ok {
		_spec.SetField(users.FieldMetadata, field.TypeJSON, value)
	}
	if uu.mutation.MetadataCleared() {
		_spec.ClearField(users.FieldMetadata, field.TypeJSON)
	}
	if uu.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.RolesTable,
			Columns: users.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedRolesIDs(); len(nodes) > 0 && !uu.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.RolesTable,
			Columns: users.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.RolesTable,
			Columns: users.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{users.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UsersUpdateOne is the builder for updating a single Users entity.
type UsersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsersMutation
}

// SetEmail sets the "email" field.
func (uuo *UsersUpdateOne) SetEmail(s string) *UsersUpdateOne {
	uuo.mutation.SetEmail(s)
	return uuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableEmail(s *string) *UsersUpdateOne {
	if s != nil {
		uuo.SetEmail(*s)
	}
	return uuo
}

// SetPasswordHash sets the "password_hash" field.
func (uuo *UsersUpdateOne) SetPasswordHash(s string) *UsersUpdateOne {
	uuo.mutation.SetPasswordHash(s)
	return uuo
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillablePasswordHash(s *string) *UsersUpdateOne {
	if s != nil {
		uuo.SetPasswordHash(*s)
	}
	return uuo
}

// SetCreatedAt sets the "created_at" field.
func (uuo *UsersUpdateOne) SetCreatedAt(t time.Time) *UsersUpdateOne {
	uuo.mutation.SetCreatedAt(t)
	return uuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableCreatedAt(t *time.Time) *UsersUpdateOne {
	if t != nil {
		uuo.SetCreatedAt(*t)
	}
	return uuo
}

// SetUpdatedAt sets the "updated_at" field.
func (uuo *UsersUpdateOne) SetUpdatedAt(t time.Time) *UsersUpdateOne {
	uuo.mutation.SetUpdatedAt(t)
	return uuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableUpdatedAt(t *time.Time) *UsersUpdateOne {
	if t != nil {
		uuo.SetUpdatedAt(*t)
	}
	return uuo
}

// SetLastLogin sets the "last_login" field.
func (uuo *UsersUpdateOne) SetLastLogin(t time.Time) *UsersUpdateOne {
	uuo.mutation.SetLastLogin(t)
	return uuo
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableLastLogin(t *time.Time) *UsersUpdateOne {
	if t != nil {
		uuo.SetLastLogin(*t)
	}
	return uuo
}

// ClearLastLogin clears the value of the "last_login" field.
func (uuo *UsersUpdateOne) ClearLastLogin() *UsersUpdateOne {
	uuo.mutation.ClearLastLogin()
	return uuo
}

// SetIsActive sets the "is_active" field.
func (uuo *UsersUpdateOne) SetIsActive(b bool) *UsersUpdateOne {
	uuo.mutation.SetIsActive(b)
	return uuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableIsActive(b *bool) *UsersUpdateOne {
	if b != nil {
		uuo.SetIsActive(*b)
	}
	return uuo
}

// SetEmailVerified sets the "email_verified" field.
func (uuo *UsersUpdateOne) SetEmailVerified(b bool) *UsersUpdateOne {
	uuo.mutation.SetEmailVerified(b)
	return uuo
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableEmailVerified(b *bool) *UsersUpdateOne {
	if b != nil {
		uuo.SetEmailVerified(*b)
	}
	return uuo
}

// SetVerificationToken sets the "verification_token" field.
func (uuo *UsersUpdateOne) SetVerificationToken(s string) *UsersUpdateOne {
	uuo.mutation.SetVerificationToken(s)
	return uuo
}

// SetNillableVerificationToken sets the "verification_token" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableVerificationToken(s *string) *UsersUpdateOne {
	if s != nil {
		uuo.SetVerificationToken(*s)
	}
	return uuo
}

// ClearVerificationToken clears the value of the "verification_token" field.
func (uuo *UsersUpdateOne) ClearVerificationToken() *UsersUpdateOne {
	uuo.mutation.ClearVerificationToken()
	return uuo
}

// SetVerificationTokenExpiry sets the "verification_token_expiry" field.
func (uuo *UsersUpdateOne) SetVerificationTokenExpiry(t time.Time) *UsersUpdateOne {
	uuo.mutation.SetVerificationTokenExpiry(t)
	return uuo
}

// SetNillableVerificationTokenExpiry sets the "verification_token_expiry" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillableVerificationTokenExpiry(t *time.Time) *UsersUpdateOne {
	if t != nil {
		uuo.SetVerificationTokenExpiry(*t)
	}
	return uuo
}

// ClearVerificationTokenExpiry clears the value of the "verification_token_expiry" field.
func (uuo *UsersUpdateOne) ClearVerificationTokenExpiry() *UsersUpdateOne {
	uuo.mutation.ClearVerificationTokenExpiry()
	return uuo
}

// SetPasswordResetToken sets the "password_reset_token" field.
func (uuo *UsersUpdateOne) SetPasswordResetToken(s string) *UsersUpdateOne {
	uuo.mutation.SetPasswordResetToken(s)
	return uuo
}

// SetNillablePasswordResetToken sets the "password_reset_token" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillablePasswordResetToken(s *string) *UsersUpdateOne {
	if s != nil {
		uuo.SetPasswordResetToken(*s)
	}
	return uuo
}

// ClearPasswordResetToken clears the value of the "password_reset_token" field.
func (uuo *UsersUpdateOne) ClearPasswordResetToken() *UsersUpdateOne {
	uuo.mutation.ClearPasswordResetToken()
	return uuo
}

// SetPasswordResetTokenExpiry sets the "password_reset_token_expiry" field.
func (uuo *UsersUpdateOne) SetPasswordResetTokenExpiry(t time.Time) *UsersUpdateOne {
	uuo.mutation.SetPasswordResetTokenExpiry(t)
	return uuo
}

// SetNillablePasswordResetTokenExpiry sets the "password_reset_token_expiry" field if the given value is not nil.
func (uuo *UsersUpdateOne) SetNillablePasswordResetTokenExpiry(t *time.Time) *UsersUpdateOne {
	if t != nil {
		uuo.SetPasswordResetTokenExpiry(*t)
	}
	return uuo
}

// ClearPasswordResetTokenExpiry clears the value of the "password_reset_token_expiry" field.
func (uuo *UsersUpdateOne) ClearPasswordResetTokenExpiry() *UsersUpdateOne {
	uuo.mutation.ClearPasswordResetTokenExpiry()
	return uuo
}

// SetMetadata sets the "metadata" field.
func (uuo *UsersUpdateOne) SetMetadata(m map[string]interface{}) *UsersUpdateOne {
	uuo.mutation.SetMetadata(m)
	return uuo
}

// ClearMetadata clears the value of the "metadata" field.
func (uuo *UsersUpdateOne) ClearMetadata() *UsersUpdateOne {
	uuo.mutation.ClearMetadata()
	return uuo
}

// AddRoleIDs adds the "roles" edge to the Roles entity by IDs.
func (uuo *UsersUpdateOne) AddRoleIDs(ids ...int) *UsersUpdateOne {
	uuo.mutation.AddRoleIDs(ids...)
	return uuo
}

// AddRoles adds the "roles" edges to the Roles entity.
func (uuo *UsersUpdateOne) AddRoles(r ...*Roles) *UsersUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uuo.AddRoleIDs(ids...)
}

// Mutation returns the UsersMutation object of the builder.
func (uuo *UsersUpdateOne) Mutation() *UsersMutation {
	return uuo.mutation
}

// ClearRoles clears all "roles" edges to the Roles entity.
func (uuo *UsersUpdateOne) ClearRoles() *UsersUpdateOne {
	uuo.mutation.ClearRoles()
	return uuo
}

// RemoveRoleIDs removes the "roles" edge to Roles entities by IDs.
func (uuo *UsersUpdateOne) RemoveRoleIDs(ids ...int) *UsersUpdateOne {
	uuo.mutation.RemoveRoleIDs(ids...)
	return uuo
}

// RemoveRoles removes "roles" edges to Roles entities.
func (uuo *UsersUpdateOne) RemoveRoles(r ...*Roles) *UsersUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uuo.RemoveRoleIDs(ids...)
}

// Where appends a list predicates to the UsersUpdate builder.
func (uuo *UsersUpdateOne) Where(ps ...predicate.Users) *UsersUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UsersUpdateOne) Select(field string, fields ...string) *UsersUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated Users entity.
func (uuo *UsersUpdateOne) Save(ctx context.Context) (*Users, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UsersUpdateOne) SaveX(ctx context.Context) *Users {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UsersUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UsersUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UsersUpdateOne) check() error {
	if v, ok := uuo.mutation.Email(); ok {
		if err := users.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Users.email": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.PasswordHash(); ok {
		if err := users.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Users.password_hash": %w`, err)}
		}
	}
	return nil
}

func (uuo *UsersUpdateOne) sqlSave(ctx context.Context) (_node *Users, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(users.Table, users.Columns, sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Users.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, users.FieldID)
		for _, f := range fields {
			if !users.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != users.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Email(); ok {
		_spec.SetField(users.FieldEmail, field.TypeString, value)
	}
	if value, ok := uuo.mutation.PasswordHash(); ok {
		_spec.SetField(users.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := uuo.mutation.CreatedAt(); ok {
		_spec.SetField(users.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.UpdatedAt(); ok {
		_spec.SetField(users.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.LastLogin(); ok {
		_spec.SetField(users.FieldLastLogin, field.TypeTime, value)
	}
	if uuo.mutation.LastLoginCleared() {
		_spec.ClearField(users.FieldLastLogin, field.TypeTime)
	}
	if value, ok := uuo.mutation.IsActive(); ok {
		_spec.SetField(users.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.EmailVerified(); ok {
		_spec.SetField(users.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.VerificationToken(); ok {
		_spec.SetField(users.FieldVerificationToken, field.TypeString, value)
	}
	if uuo.mutation.VerificationTokenCleared() {
		_spec.ClearField(users.FieldVerificationToken, field.TypeString)
	}
	if value, ok := uuo.mutation.VerificationTokenExpiry(); ok {
		_spec.SetField(users.FieldVerificationTokenExpiry, field.TypeTime, value)
	}
	if uuo.mutation.VerificationTokenExpiryCleared() {
		_spec.ClearField(users.FieldVerificationTokenExpiry, field.TypeTime)
	}
	if value, ok := uuo.mutation.PasswordResetToken(); ok {
		_spec.SetField(users.FieldPasswordResetToken, field.TypeString, value)
	}
	if uuo.mutation.PasswordResetTokenCleared() {
		_spec.ClearField(users.FieldPasswordResetToken, field.TypeString)
	}
	if value, ok := uuo.mutation.PasswordResetTokenExpiry(); ok {
		_spec.SetField(users.FieldPasswordResetTokenExpiry, field.TypeTime, value)
	}
	if uuo.mutation.PasswordResetTokenExpiryCleared() {
		_spec.ClearField(users.FieldPasswordResetTokenExpiry, field.TypeTime)
	}
	if value, ok := uuo.mutation.Metadata(); ok {
		_spec.SetField(users.FieldMetadata, field.TypeJSON, value)
	}
	if uuo.mutation.MetadataCleared() {
		_spec.ClearField(users.FieldMetadata, field.TypeJSON)
	}
	if uuo.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.RolesTable,
			Columns: users.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedRolesIDs(); len(nodes) > 0 && !uuo.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.RolesTable,
			Columns: users.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   users.RolesTable,
			Columns: users.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Users{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{users.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
